# define variables here can be pulled to othr scripts.
red=`echo -e        "\e[31m"`
green=`echo -e      "\e[32m"`
yellow=`echo -e     "\e[33m"`
blue=`echo -e       "\e[34m"`
magenta=`echo -e    "\e[35m"`
cyan=`echo -e       "\e[36m"`
white=`echo -e      "\e[37m"`

normal=`echo -e     "\e[0m"`

bred=`echo -e       "\e[1;31m"`
bgreen=`echo -e     "\e[1;32m"`
byellow=`echo -e    "\e[1;33m"`
bblue=`echo -e      "\e[1;34m"`
bmagenta=`echo -e   "\e[1;35m"`
bcyan=`echo -e      "\e[1;36m"`
bwhite=`echo -e     "\e[1;37m"`

blinkon=`echo -e      "\e[5;;m"`
blinkof=`echo -e      "\e[25;;m"`

bgred=`echo -e        "\e[41m"`
bggreen=`echo -e      "\e[42m"`
bgyellow=`echo -e     "\e[43m"`
bgblue=`echo -e       "\e[44m"`
bgmagenta=`echo -e    "\e[45m"`
bgcyan=`echo -e       "\e[46m"`
bgwhite=`echo -e      "\e[47m"`



ws=("" ":Main" ":Web" ":C0de" ":MT" ":VLC" ":LibreOffice" ":Inkscape" ":Gimp" ":WireShark" ":Ghidra")
jsonPath=$HOME/.config/i3/json/
